replicaCount: 2

image:
  repository: vijaykumar100/my-app
  tag: "3.0"
  pullPolicy: IfNotPresent

service:
  type: ingress
  port: 80
  targetPort: 80

resources:
  requests:
    memory: "128Mi"
    cpu: "256m"
  limits:
    memory: "256Mi"
    cpu: "512m"