replicaCount: 2

image:
  repository: vijaykumar100/my-app
  tag: "3.0"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8080

resources:
  requests:
    memory: "128Mi"
    cpu: "500m"
  limits:
    memory: "256Mi"
    cpu: "1000m"

ingress:
  enabled: true

serviceAccount:
  create: true  
  name: my-service-account  

autoscaling:
  enabled: true  
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
