replicaCount: 2

image:
  repository: vijaykumar100/my-app
  tag: "3.0"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  defaultBackend:
    service:
      name: my-service
      port:
        number: 80

resources:
  requests:
    memory: "128Mi"
    cpu: "256m"
  limits:
    memory: "256Mi"
    cpu: "512m"


