apiVersion: v1 
kind: Pod 
metadata:
  name: myspc-pod
  labels:
    app: spc 
spec:
  containers:
    - name: my-java-contianer
      image: "741907363630.dkr.ecr.us-west-2.amazonaws.com/dev/spcjava:latest"  
      ports:
        - containerPort: 8080