apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
      - name: spcimage
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}