apiVersion: v1
kind: Service
metadata:
  name: spc-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: spc
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
