apiVersion: v1
kind: Service
metadata:
  name: spc-app-service
spec:
  type: LoadBalancer
  ports:
    - name: http 
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: spc

