name: Continous integration
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
jobs:
  build__push:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
            languages: java

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
    
  

      - name: maven clean package
        run: |
          mvn clean package

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
            files: |
              target/surefire-reports/*.xml
      - name: Upload Trivy scan results
              
        uses: actions/upload-artifact@v4
        with:
                name: uploading jar file
                path: target/**/*.jar 

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USER_NAME}}
          password: ${{secrets.PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: sadik8143/spc:1.0

      - name: Run Trivy scan
        id: trivy_scan
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: 'sadik8143/spc:1.0'
            format: 'json'
            output: trivy-results.json 
            exit-code: '1'
            ignore-unfixed: false
            severity: 'HIGH,CRITICAL'
            continue-on-error: true
        
      - name: Upload Trivy scan results
        if: steps.trivy_scan.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
            name: trivy-scan-results
            path: trivy-results.json

      - name: pushing image
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: sadik8143/spc:1.0


             
     
        



          