name: Continous integration
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sadik8143
          password: Sadik@8143

      - name: build dockerimage
        run: |
          docker build -t sadik8143/springpetclinic:1.0 .
      - name: pushing the docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sadik8143/springpetclinic:1.0
