name: Continous integration
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
jobs:
  build__push:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'

      - name: maven clean package
        run: |
          mvn clean package

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
            files: |
              target/surefire-reports/*.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USER_NAME}}
          password: ${{secrets.PASSWORD}}


             
     
        



          