name: Java-Workflow

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: my-spc
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Build Java with Maven
        run: mvn package  
      - name: my sonar scan
                 